# Numpy Library

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]
a1 = np.array(mylist)
a1

array([1, 2, 3])

In [4]:
#Returns the number of rows and columns of the array
np.shape(a1)

(3,)

In [5]:
a2 = np.arange(1,11)
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.shape(a2)

(10,)

In [23]:
a3 = np.arange(1,11,2)
a3

array([1, 3, 5, 7, 9])

In [24]:
np.shape(a3)

(5,)

In [7]:
mymat = [[1,2,3],[4,5,6],[7,8,9]]
a4 = np.array(mymat)
a4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.shape(a4)

(3, 3)

In [10]:
a5 = np.reshape(a4, 9) 
a5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.shape(a5)

(9,)

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.full(20, 50)

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50])

In [11]:
np.full((10,10), 20)

array([[20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [19]:
#Returns the minimum value in an array
np.min(a10)

1

In [20]:
#Returns the maximum value in an array
np.max(a10)

8

In [21]:
#Returns the index of the maximum value in an array
a10.argmax()

0

In [22]:
#Returns the index of the minimum value in an array
a10.argmin()

1

# Random Functions

In [14]:
a10 = np.random.randint(0,10,5)
a10

array([8, 1, 7, 6, 3])

In [18]:
np.random.rand(5,4)

array([[0.11861961, 0.13136972, 0.54973237, 0.96344424],
       [0.34192623, 0.65251399, 0.22958085, 0.2683505 ],
       [0.33117068, 0.65298468, 0.88845676, 0.11380442],
       [0.90632177, 0.69592975, 0.26174669, 0.74975264],
       [0.49610983, 0.51490749, 0.52748502, 0.04422293]])

In [24]:
np.random.random((3,4))

array([[0.70927107, 0.22801203, 0.81863843, 0.34363791],
       [0.18425648, 0.25498344, 0.71779765, 0.61429408],
       [0.83707779, 0.2036677 , 0.13800622, 0.62274355]])

In [26]:
np.random.randn(10,10)

array([[-1.1445514 ,  0.19577244, -0.30887063,  0.15780364,  2.0014975 ,
         0.94632555, -0.05417299, -0.85273289,  0.0223901 , -0.58367309],
       [-0.4610517 ,  0.37125471, -0.21442452, -0.63702221, -0.27069599,
        -0.78382761,  0.63778768,  0.52234223,  0.19413746,  1.05808236],
       [ 1.55230756, -0.00384143,  0.31739216, -0.30780039, -0.14271265,
         0.06568738,  0.35689525,  0.82105992,  0.57106424, -0.91078205],
       [-0.55571934,  0.47595204, -0.3902644 , -1.40448342, -0.14660894,
         0.92551851,  0.25478267, -0.31542827, -0.20643888, -0.50484044],
       [-0.22220579, -0.10699969, -0.02084087, -2.4109459 ,  0.1246087 ,
        -1.15479282, -0.17987153, -1.18413272,  0.72312056,  0.89424955],
       [ 1.62288378, -0.87604692,  0.00994732, -0.18519625, -0.90090765,
        -0.46356582, -1.54661087,  0.94068029,  1.66176652, -0.32584183],
       [ 0.14592562, -0.61846214,  1.49766896,  1.62663677,  0.40778295,
        -2.22460125,  0.34837507, -0.01526416

In [28]:
from numpy.random import randint

randint(1,5,10)

array([4, 4, 1, 3, 3, 1, 3, 4, 4, 2])

In [29]:
randint(1,10,(5,5))

array([[9, 5, 8, 7, 9],
       [9, 5, 6, 3, 7],
       [5, 1, 9, 5, 3],
       [6, 6, 4, 8, 5],
       [2, 6, 1, 5, 2]])

In [31]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Array Indexing & Slicing

In [32]:
arr[6]

6

In [33]:
arr[10]

10

In [34]:
#s[start:stop:step]
arr[1:5]

array([1, 2, 3, 4])

In [35]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr2 = arr[:7]
arr2

array([0, 1, 2, 3, 4, 5, 6])

In [50]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Broadcasting (Scalar Functions)

In [52]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [54]:
arr[:] = 200
arr

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

# Slicing

In [56]:
myArray = np.arange(0,11)
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
#Changes made in the slice of an array also affect the original array
sliceOfArray = myArray[0:5]
sliceOfArray

array([0, 1, 2, 3, 4])

In [58]:
sliceOfArray[:] = 99
sliceOfArray

array([99, 99, 99, 99, 99])

In [59]:
myArray

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [60]:
#To make a separate array and leave the original one unaffected, we use the copy function
myArray2 = myArray.copy()
myArray2

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [61]:
myArray2[:] = 50
myArray2

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [62]:
myArray

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [70]:
myMat = np.arange(1,10)
myMat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
myMat2 = myMat.reshape((3,3))
myMat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
myMat2[1][1]

5

In [80]:
#arrayname[row,column]
myMat2[1,1]

5

In [75]:
myMat2[2][0]

7

**Getting subsections of a matrix**

In [78]:
myMat2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
myMat2[:2,1:]

array([[2, 3],
       [5, 6]])

In [81]:
myMat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Fancy Indexing**

We can grab the rows and columns in any order

In [83]:
myMat2[[2,0,1]]

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [84]:
myMat2[[2,1]]

array([[7, 8, 9],
       [4, 5, 6]])

In [89]:
myMat2.shape[1]

3

In [91]:
arr2d = np.zeros((5,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [96]:
arr2d.shape

(5, 10)

In [93]:
arr_length = arr2d.shape[0]
arr_length

5

# Boolean Arrays

In [11]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#Returns the boolean value depending on where the condition is True or False
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [13]:
#Returns an array of elements where the condition is True
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [14]:
#Returns only the even elements of the array
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [16]:
#Returns only the even elements of the array
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [21]:
my_arr = np.arange(1,10)
my_arr2 = my_arr.reshape(3,3)
my_arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
mylist1 = [1,2,3]
mylist2 = [4,5,6]

myArr = np.array([mylist1,mylist2])
myArr

array([[1, 2, 3],
       [4, 5, 6]])

# Reshaping Arrays Part 2

In [32]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [33]:
b.shape

(5,)

In [34]:
b2 = b.reshape(1,-1)
b2

array([[1, 2, 3, 4, 5]])

In [35]:
b2.shape

(1, 5)

In [36]:
b3 = b2.reshape(-1,)
b3

array([1, 2, 3, 4, 5])

In [37]:
b3.shape

(5,)

# **Printing an array in reverse**

In [38]:
currentArr = np.array([1,2,3,4,5,6,7,8,9,10])
currentArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
currentArr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# **Sorting The Arrays**

In [40]:
unsortedArr = np.array([40, 5, 34, 70, 25])
unsortedArr

array([40,  5, 34, 70, 25])

In [41]:
unsortedArr.sort()

In [42]:
unsortedArr

array([ 5, 25, 34, 40, 70])

In [47]:
#sort sorts the elements within the original array
#sort is a function of numpy
type(unsortedArr)

numpy.ndarray

In [43]:
myArray = np.array([5,3,7,4,6])
myArray

array([5, 3, 7, 4, 6])

In [45]:
myArray2 = sorted(myArray)
myArray2

[3, 4, 5, 6, 7]

In [46]:
#sorted returns a new list with the sorted elements
#sorted is an in-built function of Python
type(myArray2)

list

In [49]:
x = np.argsort(myArray)
x

array([1, 3, 0, 4, 2])

# Array Math

In [50]:
#Performing arithmetic operations on the elements of the arrays

a1 = np.array([10,20])
a2 = np.array([30])

a1+a2

array([40, 50])

In [51]:
a1-a2

array([-20, -10])

In [52]:
a1*a2

array([300, 600])

In [53]:
a1/a2

array([0.33333333, 0.66666667])

In [54]:
a1%a2

array([10, 20])

In [62]:
a3 = np.array([1,2,3,4])
a4 = np.array([2,3,4,5])

a3%a4

array([1, 2, 3, 4])

In [63]:
a5 = np.array([1,2,3,4])
a6 = np.array([0])

a5/a6

<ipython-input-63-6cdfbfb0c6bd>:4: RuntimeWarning: divide by zero encountered in true_divide
  a5/a6


array([inf, inf, inf, inf])

In [64]:
a6/a5

array([0., 0., 0., 0.])

# Universal Array Functions 

In [4]:
myArray = np.array([1, 4, 9, 16, 25])
myArray

array([ 1,  4,  9, 16, 25])

In [5]:
np.sqrt(myArray)

array([1., 2., 3., 4., 5.])

In [6]:
np.exp(myArray)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10])

In [7]:
np.max(myArray)

25

In [8]:
np.min(myArray)

1

In [9]:
np.sin(myArray)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175])

In [10]:
np.cos(myArray)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948,  0.99120281])

In [11]:
np.log(myArray)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582])

In [12]:
np.tan(myArray)

array([ 1.55740772,  1.15782128, -0.45231566,  0.30063224, -0.13352641])

In [13]:
np.abs(np.cos(myArray))

array([0.54030231, 0.65364362, 0.91113026, 0.95765948, 0.99120281])

In [14]:
for x in myArray:
    print(x)

1
4
9
16
25
