In [1]:
#Importing the libraries
import numpy as np

#Creating the board
board = np.full((3,3), 2)
movesDict = {1:[0,0], 2:[0,1], 3:[0,2], 4:[1,0], 5:[1,1], 6:[1,2], 7:[2,0], 8:[2,1], 9:[2,2]}


#User defined functions
def printBoard():
    print("")
    print(board)
    print("")
    
def playGame():
    turn = 1
    count = 0
    
    for num in range(10):
        printBoard()
        
        if count==9:
            break
            
        move = int( input("Which place do you want to play " +str(turn)+ "? ") )
        if move<1 or move>9:
            print("Invalid move")
            continue
            
        realMove = movesDict.get(move, "Invalid value")
        #Example move=7
        #realMove = [2,0]
        #print(realMove)
        #print(type(realMove))
        row = realMove[0]
        col = realMove[1]
        #print("Row: ", row)
        #print("Column: ", col)
        
        #Checking if the place is empty
        if board[row][col]==2:
            board[row][col]=turn
            winner = checkWin(turn)
            
            if winner!="":
                printBoard()
                print("Winner is " +str(turn)+ "!")
                break
            else:
                count += 1
                if turn==1:
                    turn=0
                else:
                    turn=1
            
            
            
        else:
            print("That place is already filled")
            continue
            

def checkWin(turn):
    winner = ""
    
    #Checking rows
    
    #Checking columns
    
    #Checking diagonals
    
    #No winner
    
    return winner
        
    
#Main function
playGame()


[[2 2 2]
 [2 2 2]
 [2 2 2]]

Which place do you want to play 1? 5

[[2 2 2]
 [2 1 2]
 [2 2 2]]

Which place do you want to play 1? 4

[[2 2 2]
 [1 1 2]
 [2 2 2]]

Which place do you want to play 1? 4
That place is already filled

[[2 2 2]
 [1 1 2]
 [2 2 2]]

Which place do you want to play 1? 7

[[2 2 2]
 [1 1 2]
 [1 2 2]]

Which place do you want to play 1? 9

[[2 2 2]
 [1 1 2]
 [1 2 1]]

Which place do you want to play 1? 7
That place is already filled

[[2 2 2]
 [1 1 2]
 [1 2 1]]



KeyboardInterrupt: Interrupted by user